---
- name: Build Docker Image for Portfolio App
  hosts: Workstation
  connection: local
  gather_facts: false
  become: true

  vars:
    image_name: portfolio-app
    image_tag: latest
    tarball_path: /tmp/portfolio-app.tar   # use /tmp which always exists

  tasks:
    - name: Build the Docker image from the Dockerfile
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: .
          dockerfile: dockerfile
        state: present
      register: build_result
      failed_when: build_result.failed

    - name: Display build status
      debug:
        msg: "Docker image '{{ image_name }}:{{ image_tag }}' built successfully."
      when: build_result.changed

    - name: Save docker image to tarball
      command: docker save -o {{ tarball_path }} {{ image_name }}:{{ image_tag }}

    - name: Fetch tarball back to control machine
      fetch:
        src: "{{ tarball_path }}"
        dest: "./portfolio-app.tar"
        flat: yes



