---
- name: Deploy and Run Portfolio App (Build on Target)
  hosts: centos:ubuntu
  become: true
  gather_facts: true

  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true
      when: ansible_distribution in ['CentOS', 'Ubuntu']

    # Step 1: Create a folder on the server to hold our files
    - name: Create app directory on remote server
      file:
        path: /opt/portfolio-app
        state: directory
        mode: '0755'

    # Step 2: Copy index.html and Dockerfile to the server
    - name: Copy app files to remote server
      copy:
        src: "{{ item }}"
        dest: /opt/portfolio-app/
      loop:
        - index.html
        - Dockerfile

    # Step 3: Build the image RIGHT HERE on the server
    - name: Build the Docker image on the remote server
      docker_image:
        name: portfolio-app
        tag: latest
        source: build
        build:
          path: /opt/portfolio-app # Build from the folder we just filled
        state: present
        force_source: true # Force rebuild to pick up changes

    # Step 4: Run the container
    - name: Run the portfolio-app container
      docker_container:
        name: portfolio-container
        image: portfolio-app:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:80"
        detach: true
